CREATE TABLE USER_INFO ( USER_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
LOGIN_NAME NVARCHAR(50) not null,
 PASS NVARCHAR(50) not null,
 ENCODE_PASS NVARCHAR(100) not null,
 LOGIN_TIME DATETIME not null,
 LOGIN_STATUS INT not null );
 
 use phanhiep;
 drop table USER_INFO;